In [5]:
import joblib as jbl

jbl.load("models/temperature_Metadata_N_12_P_11_bs_32.jbl")

{'neurons': 12,
 'centers': array([[ 5.21295156e-01,  4.78345649e-01,  4.36248647e-01,
          5.33752706e-01,  5.00000000e-01],
        [ 2.66129620e-01,  2.63505140e-01,  8.43864117e-01,
          8.50735153e-01,  5.00000000e-01],
        [ 5.03770073e-01,  5.05268637e-01,  8.40472428e-01,
          8.40669966e-01, -5.55111512e-17],
        [ 4.80123617e-01,  4.98991542e-01,  7.45325901e-01,
          7.00814751e-01,  1.00000000e+00],
        [ 8.25456630e-01,  8.19436481e-01,  2.21010581e-01,
          2.26220039e-01,  1.00000000e+00],
        [ 5.89986257e-01,  5.88955522e-01,  6.53656126e-01,
          6.51968050e-01, -1.44328993e-15],
        [ 5.73154312e-01,  5.74425911e-01,  2.37748965e-01,
          2.20148886e-01,  5.00000000e-01],
        [ 6.51955363e-01,  6.53212024e-01,  4.27080572e-01,
          4.33408428e-01, -1.05471187e-15],
        [ 6.82675696e-01,  7.01782876e-01,  4.56640554e-01,
          4.03192749e-01,  1.00000000e+00],
        [ 3.97658661e-01,  3.87427881

In [6]:
import tensorflow as tf

In [11]:
import numpy as np



In [18]:
import numpy as np

inputs = np.array([0.0, 0.0, 0.0, 0.0, 0.0])
temp = predict(inputs, "models/temperature_Metadata_N_12_P_11_bs_32.jbl", "models/temperature_RBF_ANN_model_bs_32_N_12_P_11.h5")

1/1 [==============================] - 0s 74ms/step


2023-03-02 22:27:16.433237: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [19]:
temp

array([[0.3461448]], dtype=float32)

In [3]:
import base64
from IPython.display import Image, display
import matplotlib.pyplot as plt

def mm(graph):
  graphbytes = graph.encode("ascii")
  base64_bytes = base64.b64encode(graphbytes)
  base64_string = base64_bytes.decode("ascii")
  display(Image(url=f"https://mermaid.ink/img/{base64_string}"))

mm("""
graph LR;
    A--> B & C & D;
    B--> A & E;
    C--> A & E;
    D--> A & E;
    E--> B & C & D;
""")

In [6]:
humidity_data = jbl.load('models/all_humidity_data.joblib')

In [7]:
humidity_data

{'modified_data_orig':        T-1  T-24   H-1  H-24  Season  Humidity(H)
 0     62.0  65.0  89.0  90.0     1.0         90.0
 1     65.0  65.0  90.0  90.0     1.0         90.0
 2     65.0  65.0  90.0  90.0     1.0         90.0
 3     65.0  78.0  90.0  49.0     1.0         48.0
 4     78.0  78.0  48.0  49.0     1.0         48.0
 ...    ...   ...   ...   ...     ...          ...
 8731  67.0  69.0  92.0  88.0     1.0         92.0
 8732  67.0  69.0  92.0  88.0     1.0         92.0
 8733  67.0  65.0  92.0  94.0     1.0         94.0
 8734  65.0  65.0  94.0  94.0     1.0         94.0
 8735  65.0  65.0  94.0  94.0     1.0         94.0
 
 [8736 rows x 6 columns],
 'humidity_x_scalar': MinMaxScaler(),
 'humidity_y_scalar': MinMaxScaler(),
 'humidity_x_data_scaled': array([[0.20689655, 0.25862069, 0.85227273, 0.86363636, 0.5       ],
        [0.25862069, 0.25862069, 0.86363636, 0.86363636, 0.5       ],
        [0.25862069, 0.25862069, 0.86363636, 0.86363636, 0.5       ],
        ...,
        [0.29

In [10]:
from predict import predict
import numpy as np

inputs = np.array([89.6, 91.4, 97, 98, 0])
humidity = humidity_data['humidity_y_scalar'].inverse_transform(predict(inputs, "models/humidity_Metadata_N_12_P_10_bs_128.jbl", "models/humidity_RBF_ANN_model_bs_128_N_12_P_10.h5"))


2023-03-06 12:10:28.152308: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-06 12:10:28.152823: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-03-06 12:10:28.346575: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB

1/1 [==============================] - 0s 101ms/step


2023-03-06 12:10:28.406845: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [11]:
humidity

array([[29.749146]], dtype=float32)

In [17]:
y_hat = predict(inputs, "models/humidity_Metadata_N_12_P_10_bs_128.jbl", "models/humidity_RBF_ANN_model_bs_128_N_12_P_10.h5")
y_hat

1/1 [==============================] - 0s 32ms/step


2023-03-06 12:15:30.419909: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[0.17896757]], dtype=float32)

In [13]:
y_scalar = humidity_data['humidity_y_scalar']

In [18]:
(y_scalar.data_max_ - y_scalar.data_min_) * y_hat + y_scalar.data_min_

array([[29.74914575]])